Add pipeline check for missing __init__.py in sonic-xcvrd whl package (#593)
Description
Ensure that the pipeline fail to build if sonic-xcvrd whl package is missing init.py file.

Motivation and Context
The __init__.py file is necessary in each directory to indicate that the directory should be treated as a package.
Tools like setuptools and find_packages() rely on the presence of __init__.py files to identify packages and subpackages.
Without __init__.py files, the directories will not be included in the package distribution, leading to incomplete or broken packages.
By ensuring that each directory contains an __init__.py file, we can create a complete and functional Python wheel package.

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -126,6 +126,17 @@ jobs:
       # Python 3
       - ${{ if eq(project.python3, true) }}:
         - script: |
+            set -xe
+            # Check for missing __init__.py files for sonic-xcvrd
+            if [ "${{ project.name }}" == "xcvrd" ]; then
+                XCVRD_WORK_DIR=$(System.DefaultWorkingDirectory)/${{ project.root_dir }}/xcvrd
+                missing_init_files=$(find $XCVRD_WORK_DIR -type d ! -exec test -e "{}/__init__.py" \; -print)
+                if [ -n "$missing_init_files" ]; then
+                  echo "Error: The following directories are missing __init__.py files:"
+                  echo "$missing_init_files"
+                  exit 1
+                fi
+            fi
             python3 setup.py test
           workingDirectory: ${{ project.root_dir }}
           displayName: '${{ project.name }}(Py3) Test'
